// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheGodfather.Database;

namespace TheGodfather.Migrations
{
    [DbContext(typeof(TheGodfatherDbContext))]
    [Migration("20200724155543_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gf")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TheGodfather.Database.Models.AutoRole", b =>
                {
                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleIdDb")
                        .HasColumnName("rid")
                        .HasColumnType("bigint");

                    b.HasKey("GuildIdDb", "RoleIdDb");

                    b.ToTable("auto_roles");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.BankAccount", b =>
                {
                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<long>("UserIdDb")
                        .HasColumnName("uid")
                        .HasColumnType("bigint");

                    b.Property<long>("Balance")
                        .HasColumnName("balance")
                        .HasColumnType("bigint");

                    b.HasKey("GuildIdDb", "UserIdDb");

                    b.ToTable("bank_accounts");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.Birthday", b =>
                {
                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<long>("ChannelIdDb")
                        .HasColumnName("cid")
                        .HasColumnType("bigint");

                    b.Property<long>("UserIdDb")
                        .HasColumnName("uid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnName("date")
                        .HasColumnType("date");

                    b.Property<int>("LastUpdateYear")
                        .HasColumnName("last_update_year")
                        .HasColumnType("integer");

                    b.HasKey("GuildIdDb", "ChannelIdDb", "UserIdDb");

                    b.ToTable("birthdays");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.BlockedChannel", b =>
                {
                    b.Property<long>("ChannelIdDb")
                        .HasColumnName("cid")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("reason")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64)
                        .HasDefaultValue(null);

                    b.HasKey("ChannelIdDb");

                    b.ToTable("blocked_channels");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.BlockedUser", b =>
                {
                    b.Property<long>("UserIdDb")
                        .HasColumnName("uid")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("reason")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64)
                        .HasDefaultValue(null);

                    b.HasKey("UserIdDb");

                    b.ToTable("blocked_users");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.BotStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Activity")
                        .HasColumnName("activity_type")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnName("status")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("bot_statuses");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.Chicken", b =>
                {
                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<long>("UserIdDb")
                        .HasColumnName("uid")
                        .HasColumnType("bigint");

                    b.Property<int>("BareMaxVitality")
                        .HasColumnName("max_vit")
                        .HasColumnType("integer");

                    b.Property<int>("BareStrength")
                        .HasColumnName("str")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.Property<int>("Vitality")
                        .HasColumnName("vit")
                        .HasColumnType("integer");

                    b.HasKey("GuildIdDb", "UserIdDb");

                    b.ToTable("chickens");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.ChickenBoughtUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("integer");

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<long>("UserIdDb")
                        .HasColumnName("uid")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "GuildIdDb", "UserIdDb");

                    b.HasIndex("GuildIdDb", "UserIdDb");

                    b.ToTable("chicken_bought_upgrades");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.ChickenUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("Cost")
                        .HasColumnName("cost")
                        .HasColumnType("bigint");

                    b.Property<int>("Modifier")
                        .HasColumnName("mod")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.Property<int>("UpgradesStat")
                        .HasColumnName("stat")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("chicken_upgrades");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.CommandRule", b =>
                {
                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<long>("ChannelIdDb")
                        .HasColumnName("cid")
                        .HasColumnType("bigint");

                    b.Property<string>("Command")
                        .HasColumnName("command")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.Property<bool>("Allowed")
                        .HasColumnName("allow")
                        .HasColumnType("boolean");

                    b.HasKey("GuildIdDb", "ChannelIdDb", "Command");

                    b.ToTable("cmd_rules");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.EmojiReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnName("reaction")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("GuildIdDb");

                    b.ToTable("reactions_emoji");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.EmojiReactionTrigger", b =>
                {
                    b.Property<int>("ReactionId")
                        .HasColumnName("id")
                        .HasColumnType("integer");

                    b.Property<string>("Trigger")
                        .HasColumnName("trigger")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("ReactionId", "Trigger");

                    b.ToTable("reactions_emoji_triggers");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.ExemptedAntispamEntity", b =>
                {
                    b.Property<long>("IdDb")
                        .HasColumnName("xid")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<byte>("Type")
                        .HasColumnName("type")
                        .HasColumnType("smallint");

                    b.HasKey("IdDb", "GuildIdDb", "Type");

                    b.HasIndex("GuildIdDb");

                    b.ToTable("exempt_antispam");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.ExemptedLoggingEntity", b =>
                {
                    b.Property<long>("IdDb")
                        .HasColumnName("xid")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<byte>("Type")
                        .HasColumnName("type")
                        .HasColumnType("smallint");

                    b.HasKey("IdDb", "GuildIdDb", "Type");

                    b.HasIndex("GuildIdDb");

                    b.ToTable("exempt_logging");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.ExemptedRatelimitEntity", b =>
                {
                    b.Property<long>("IdDb")
                        .HasColumnName("xid")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<byte>("Type")
                        .HasColumnName("type")
                        .HasColumnType("smallint");

                    b.HasKey("IdDb", "GuildIdDb", "Type");

                    b.HasIndex("GuildIdDb");

                    b.ToTable("exempt_ratelimit");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.Filter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<string>("TriggerString")
                        .IsRequired()
                        .HasColumnName("trigger")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("GuildIdDb");

                    b.ToTable("filters");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.ForbiddenName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<string>("RegexString")
                        .IsRequired()
                        .HasColumnName("name_regex")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("GuildIdDb");

                    b.ToTable("forbidden_names");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.GameStats", b =>
                {
                    b.Property<long>("UserIdDb")
                        .HasColumnName("uid")
                        .HasColumnType("bigint");

                    b.Property<int>("AnimalRacesWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ar_won")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("CaroLost")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("caro_lost")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("CaroWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("caro_won")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Chain4Lost")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("c4_lost")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Chain4Won")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("c4_won")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("DuelLost")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("duel_lost")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("DuelWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("duel_won")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("HangmanWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("hangman_won")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("NumberRacesWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nr_won")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("OthelloLost")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("othello_lost")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("OthelloWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("othello_won")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("QuizWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("quiz_won")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TicTacToeLost")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ttt_lost")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TicTacToeWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ttt_won")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("UserIdDb");

                    b.ToTable("game_stats");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.GuildConfig", b =>
                {
                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<short>("AntiInstantLeaveCooldown")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("antiinstantleave_cooldown")
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)3);

                    b.Property<bool>("AntiInstantLeaveEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("antiinstantleave_enabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte>("AntifloodAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("antiflood_action")
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)4);

                    b.Property<short>("AntifloodCooldown")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("antiflood_cooldown")
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)10);

                    b.Property<bool>("AntifloodEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("antiflood_enabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<short>("AntifloodSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("antiflood_sensitivity")
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)5);

                    b.Property<byte>("AntispamAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("antispam_action")
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<bool>("AntispamEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("antispam_enabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<short>("AntispamSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("antispam_sensitivity")
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)5);

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("currency")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32)
                        .HasDefaultValue(null);

                    b.Property<long?>("LeaveChannelIdDb")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("leave_cid")
                        .HasColumnType("bigint")
                        .HasDefaultValue(null);

                    b.Property<string>("LeaveMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("leave_msg")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128)
                        .HasDefaultValue(null);

                    b.Property<bool>("LinkfilterBootersEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("linkfilter_booters")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("LinkfilterDiscordInvitesEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("linkfilter_invites")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LinkfilterDisturbingWebsitesEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("linkfilter_disturbing")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("LinkfilterEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("linkfilter_enabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LinkfilterIpLoggersEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("linkfilter_loggers")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("LinkfilterUrlShortenersEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("linkfilter_shorteners")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Locale")
                        .HasColumnName("locale")
                        .HasColumnType("character varying(8)")
                        .HasMaxLength(8);

                    b.Property<long?>("LogChannelIdDb")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("log_cid")
                        .HasColumnType("bigint")
                        .HasDefaultValue(null);

                    b.Property<long?>("MuteRoleIdDb")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("mute_rid")
                        .HasColumnType("bigint")
                        .HasDefaultValue(null);

                    b.Property<string>("Prefix")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("prefix")
                        .HasColumnType("character varying(8)")
                        .HasMaxLength(8)
                        .HasDefaultValue(null);

                    b.Property<byte>("RatelimitAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ratelimit_action")
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<bool>("RatelimitEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ratelimit_enabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<short>("RatelimitSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ratelimit_sensitivity")
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)5);

                    b.Property<bool>("ReactionResponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("silent_response_enabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("SuggestionsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("suggestions_enabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TimezoneId")
                        .HasColumnName("timezone_id")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.Property<long?>("WelcomeChannelIdDb")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("welcome_cid")
                        .HasColumnType("bigint")
                        .HasDefaultValue(null);

                    b.Property<string>("WelcomeMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("welcome_msg")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128)
                        .HasDefaultValue(null);

                    b.HasKey("GuildIdDb");

                    b.ToTable("guild_cfg");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.GuildTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("ExecutionTime")
                        .HasColumnName("execution_time")
                        .HasColumnType("timestamptz");

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<long?>("RoleIdDb")
                        .HasColumnName("rid")
                        .HasColumnType("bigint");

                    b.Property<byte>("Type")
                        .HasColumnName("type")
                        .HasColumnType("smallint");

                    b.Property<long>("UserIdDb")
                        .HasColumnName("uid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildIdDb");

                    b.ToTable("scheduled_tasks");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.Insult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("content")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildIdDb");

                    b.ToTable("insults");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.Meme", b =>
                {
                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("url")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("GuildIdDb", "Name");

                    b.ToTable("memes");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.PrivilegedUser", b =>
                {
                    b.Property<long>("UserIdDb")
                        .HasColumnName("uid")
                        .HasColumnType("bigint");

                    b.HasKey("UserIdDb");

                    b.ToTable("privileged_users");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.PurchasableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<long>("Price")
                        .HasColumnName("price")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildIdDb");

                    b.ToTable("purchasable_items");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.PurchasedItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnName("id")
                        .HasColumnType("integer");

                    b.Property<long>("UserIdDb")
                        .HasColumnName("uid")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId", "UserIdDb");

                    b.ToTable("purchased_items");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("ChannelIdDb")
                        .HasColumnName("cid")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ExecutionTime")
                        .HasColumnName("execution_time")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsRepeating")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_repeating")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnName("message")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<TimeSpan?>("RepeatIntervalDb")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("repeat_interval")
                        .HasColumnType("interval")
                        .HasDefaultValue(new TimeSpan(0, 0, 0, 0, -1));

                    b.Property<long>("UserIdDb")
                        .HasColumnName("uid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("reminders");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.RssFeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("LastPostUrl")
                        .IsRequired()
                        .HasColumnName("last_post_url")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("rss_feeds");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.RssSubscription", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("integer");

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<long>("ChannelIdDb")
                        .HasColumnName("cid")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.HasKey("Id", "GuildIdDb", "ChannelIdDb");

                    b.HasIndex("GuildIdDb");

                    b.ToTable("rss_subscriptions");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.SelfRole", b =>
                {
                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleIdDb")
                        .HasColumnName("rid")
                        .HasColumnType("bigint");

                    b.HasKey("GuildIdDb", "RoleIdDb");

                    b.ToTable("self_roles");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.SwatPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnName("additional_info")
                        .HasColumnType("text");

                    b.Property<bool>("IsBlacklisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_blacklisted")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("swat_players");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.SwatPlayerAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasColumnName("alias")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.Property<int>("PlayerId")
                        .HasColumnName("id")
                        .HasColumnType("integer");

                    b.HasKey("Alias", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("swat_aliases");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.SwatPlayerIP", b =>
                {
                    b.Property<string>("IP")
                        .HasColumnName("ip")
                        .HasColumnType("character varying(16)")
                        .HasMaxLength(16);

                    b.Property<int>("PlayerId")
                        .HasColumnName("id")
                        .HasColumnType("integer");

                    b.HasKey("IP", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("swat_ips");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.SwatServer", b =>
                {
                    b.Property<string>("IP")
                        .HasColumnName("ip")
                        .HasColumnType("character varying(16)")
                        .HasMaxLength(16);

                    b.Property<int>("JoinPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("join_port")
                        .HasColumnType("integer")
                        .HasDefaultValue(10480);

                    b.Property<int>("QueryPort")
                        .HasColumnName("query_port")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.HasKey("IP", "JoinPort", "QueryPort");

                    b.ToTable("swat_servers");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.TextReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnName("reaction")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("GuildIdDb");

                    b.ToTable("reactions_text");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.TextReactionTrigger", b =>
                {
                    b.Property<int>("ReactionId")
                        .HasColumnName("id")
                        .HasColumnType("integer");

                    b.Property<string>("Trigger")
                        .HasColumnName("trigger")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("ReactionId", "Trigger");

                    b.ToTable("reactions_text_triggers");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.XpCount", b =>
                {
                    b.Property<long>("UserIdDb")
                        .HasColumnName("uid")
                        .HasColumnType("bigint");

                    b.Property<int>("XpDb")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("xp")
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("UserIdDb");

                    b.ToTable("xp_count");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.XpRank", b =>
                {
                    b.Property<long>("GuildIdDb")
                        .HasColumnName("gid")
                        .HasColumnType("bigint");

                    b.Property<short>("Rank")
                        .HasColumnName("rank")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.HasKey("GuildIdDb", "Rank");

                    b.ToTable("guild_ranks");
                });

            modelBuilder.Entity("TheGodfather.Database.Models.AutoRole", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("AutoRoles")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.BankAccount", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("Accounts")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.Birthday", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("Birthdays")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.Chicken", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("Chickens")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.ChickenBoughtUpgrade", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", null)
                        .WithMany("ChickenBoughtUpgrades")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheGodfather.Database.Models.ChickenUpgrade", "Upgrade")
                        .WithMany("BoughtUpgrades")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheGodfather.Database.Models.Chicken", "Chicken")
                        .WithMany("Upgrades")
                        .HasForeignKey("GuildIdDb", "UserIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.CommandRule", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("CommandRules")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.EmojiReaction", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("EmojiReactions")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.EmojiReactionTrigger", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.EmojiReaction", "Reaction")
                        .WithMany("DbTriggers")
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.ExemptedAntispamEntity", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("ExemptsAntispam")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.ExemptedLoggingEntity", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("ExemptsLogging")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.ExemptedRatelimitEntity", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("ExemptsRatelimit")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.Filter", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("Filters")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.ForbiddenName", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("ForbiddenNames")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.GuildTask", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("GuildTasks")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.Insult", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("Insults")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.Meme", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("Memes")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.PurchasableItem", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("PurchasableItems")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.PurchasedItem", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.PurchasableItem", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.RssSubscription", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("Subscriptions")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheGodfather.Database.Models.RssFeed", "Feed")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.SelfRole", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("SelfRoles")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.SwatPlayerAlias", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.SwatPlayer", "Player")
                        .WithMany("DbAliases")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.SwatPlayerIP", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.SwatPlayer", "Player")
                        .WithMany("DbIPs")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.TextReaction", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("TextReactions")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.TextReactionTrigger", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.TextReaction", "Reaction")
                        .WithMany("DbTriggers")
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheGodfather.Database.Models.XpRank", b =>
                {
                    b.HasOne("TheGodfather.Database.Models.GuildConfig", "GuildConfig")
                        .WithMany("Ranks")
                        .HasForeignKey("GuildIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
