#region USING_DIRECTIVES
using System.Collections.Generic;
using System.Collections.Immutable;
#endregion

namespace TheGodfather.EventListeners.Common
{
    public static class SuspiciousSites
    {
        public static readonly LinkfilterMatcher IpLoggerMatcher = new LinkfilterMatcher(
        #region IP_LOGGERS
            "02ip.ru",
            "2no.co",
            "ampnode.host",
            "anonymousforum.pw",
            "aruljohn.com/widget/ip/",
            "aruljohn.com/widget/zip/",
            "battlė.net",
            "bbcnews.today",
            "blasze.tk",
            "bvog.com",
            "cloudfsx.com",
            "community.hackersclub.net",
            "cubeupload.com",
            "cubeupload.xyz",
            "dank.host",
            "deviantartt.ga",
            "deviantartt.ml",
            "dropbox.desi",
            "dropboxx.cf",
            "dropboxx.ga",
            "dropboxx.lm ",
            "exploit-db.xyz",
            "ezstat.ru",
            "files.uploads.ws",
            "fotocerdas.com",
            "freeanonymous.host",
            "grabify.link",
            "gtadb.net",
            "gyazoo.ga",
            "gyazoo.xyz",
            "hackernews.online",
            "hackfȯrums.com",
            "hackfȯrums.net",
            "hdblog.tech",
            "hondachat.com",
            "hostingonline.desi",
            "hs.vc",
            "imageshack.ml",
            "imgurl.us",
            "imgúr.com",
            "ip-grabber.com",
            "ip.jlynx.net",
            "ipddoser.xyz",
            "iplis.ru",
            "iplo.ru",
            "iplogger.com",
            "iplogger.info",
            "iplogger.org",
            "iplogger.ru",
            "ipsnatcher.com",
            "leakforum.ga",
            "linkit.cf",
            "login.anal-porn.info",
            "media.appspot.com",
            "myiptest.com/img.php",
            "panel.teamspeak.bz	",
            "parlament.usa.cc",
            "paypal.sellbitcoins.com",
            "pgrabber.ru",
            "postimage.co",
            "printscr.ga",
            "privatexmpp.me",
            "prntsc.cf",
            "ps3cfw.com",
            "r1p.pw",
            "sciencefuture.tk",
            "sexy18.webcam",
            "skidpaste.org",
            "skypecracker.xyz",
            "skypegrab.net",
            "spoofing.host",
            "strawpoll.ga",
            "strawpolll.ga",
            "stresser.science",
            "topcdn.biz",
            "topstreaming.us",
            "ts3free.top",
            "twitte.ga",
            "viphackforum.xyz",
            "viphackforums.xyz",
            "webprofile.me",
            "xxox.co.uk",
            "youramonkey.com",
            "youutube.gq"
        #endregion
        );

        public static readonly LinkfilterMatcher BooterMatcher = new LinkfilterMatcher(
        #region BOOTERS
            "bootyou.net",
            "critical-boot.com",
            "ddos.city",
            "freebooter.pro",
            "networkstresser.com",
            "orboot.pw",
            "orcahub.com",
            "oxystress.eu",
            "restresser.com",
            "vbooter.org",
            "vdos-s.com"
        #endregion
        );

        public static readonly LinkfilterMatcher DisturbingWebsiteMatcher = new LinkfilterMatcher(
        #region DISTURBING_SITES
            "2girls1cup.com",
            "420yolo.com",
            "absolu-flash.com/horror-games/index.php?rubrique=peur",
            "agor.io",
            "akk.li",
            "albinoblacksheep.com/flash/chris2.php",
            "albinoblacksheep.com/flash/chris3.php",
            "albinoblacksheep.com/flash/halloween.php",
            "albinoblacksheep.com/flash/handeye.php",
            "albinoblacksheep.com/flash/inkblot.php",
            "albinoblacksheep.com/flash/kikia.php",
            "albinoblacksheep.com/flash/sajjad.php",
            "albinoblacksheep.com/flash/sayit.php",
            "albinoblacksheep.com/flash/subliminal",
            "albinoblacksheep.com/flash/vision.php",
            "albinoblacksheep.com/flash/waldo.php",
            "alienatedmedia.com/xperiments/happyhalloween",
            "alienredwolf.com",
            "alienredwolf.com/watch/thisisneville.html",
            "anne.jpg",
            "armorgames.com/play/2521/ghostscape",
            "avatarmagic.com/fingertwister/game.php",
            "ballsack.org",
            "bestgore.com",
            "bestshockers.com/1-guy-1-screwdriver",
            "bluewaffle.net",
            "brainpop.com/socialstudies/culture/halloween",
            "collegegags.com/index.php/collegegags/displaycontent/scare_prank",
            "computerpranks.com/download/online-fun/color.swf",
            "discharges.org",
            "dragonsplace.co.uk/flash/colourblind.html",
            "dragonsplace.co.uk/flash/sheep.html",
            "ebaumsworld.com/2006/03/lightning.html",
            "ebaumsworld.com/albanude.html",
            "ethereality.info/ethereality_website/paintings_drawings/new/illustrations/melancholic_princess/melancholic_princess.htm",
            "fbcdn-sphotos-g-a.cloudliv.net/hphotos-ak-ash4/2836620_371023452991370_441600357_n.jpg",
            "fearnest.ru",
            "fetchfido.co.uk/games/kikia/kikia.htm",
            "filecabi.net/video/london-ghost.html",
            "findminecraft.com",
            "freeonlinegames.com/play/1560.html",
            "freewebs.com/jesposworld/weirdspidermancomic.htm",
            "funny-spot.com/html/whats-wrong-with-this-picture.html",
            "funnyjunk.com/pages/image.htm",
            "funnyjunk.com/pages/watch.htm",
            "funshack.com/scary.html",
            "geocities.com/patlee_69",
            "ghostboy.co.uk/ghostboywho.htm",
            "go.interwebline.de/shock/o_13.php",
            "goatse.fr",
            "goatse.info",
            "goatse.ru",
            "gorekiller.newgrounds.com",
            "hai2u.com",
            "happypuppies.net",
            "haunted.org/html/fright_gauge.html",
            "herobrine.com",
            "home22.inet.tele.dk/flash/swf/gamemun.swf",
            "icarly.com/ivideo/index.html#vid4602",
            "img101.imageshack.us/my.php?image=dancincats5ze.swf",
            "img342.imageshack.us/my.php?image=beach7fa.swf",
            "img489.imageshack.us/my.php?image=sadness3kr.swf",
            "jarsquatter.com",
            "jkcinema.com",
            "jultavling.se",
            "k-fee.com",
            "killsometime.com/animations/animation.asp?id=119",
            "killwithme.com",
            "killwithus.com",
            "kontraband.com/show/show.asp?id=2320&cat=games&nsfw=0&rtn=search-2320&keywords=spooky%20ro",
            "lemonparty.org",
            "liquidgeneration.com/content/a55hat.aspx?cid=1103",
            "liquidgeneration.com/content/a55hat.aspx?cid=1131",
            "liquidgeneration.com/content/a55hat.aspx?cid=1177",
            "liquidgeneration.com/content/a55hat.aspx?cid=1183",
            "liquidgeneration.com/content/a55hat.aspx?cid=1215",
            "liquidgeneration.com/content/a55hat.aspx?cid=1329",
            "liquidgeneration.com/content/a55hat.aspx?cid=1483",
            "liquidgeneration.com/content/a55hat.aspx?cid=1515",
            "liquidgeneration.com/content/a55hat.aspx?cid=1591",
            "liquidgeneration.com/content/a55hat.aspx?cid=1620",
            "liquidgeneration.com/content/a55hat.aspx?cid=1707",
            "liquidgeneration.com/content/a55hat.aspx?cid=1883",
            "liquidgeneration.com/content/a55hat.aspx?cid=1956",
            "liquidgeneration.com/content/a55hat.aspx?cid=228",
            "liquidgeneration.com/content/a55hat.aspx?cid=236",
            "liquidgeneration.com/content/a55hat.aspx?cid=241",
            "liquidgeneration.com/content/a55hat.aspx?cid=311",
            "liquidgeneration.com/content/a55hat.aspx?cid=341",
            "liquidgeneration.com/content/a55hat.aspx?cid=506",
            "liquidgeneration.com/content/a55hat.aspx?cid=567",
            "liquidgeneration.com/content/a55hat.aspx?cid=671",
            "liquidgeneration.com/content/a55hat.aspx?cid=709",
            "liquidgeneration.com/content/a55hat.aspx?cid=828",
            "liquidgeneration.com/content/a55hat.aspx?cid=897",
            "liquidgeneration.com/content/a55hat.aspx?cid=922",
            "liquidgeneration.com/content/a55hat.aspx?cid=950",
            "liquidgeneration.com/content/showmedacontent.aspx?cid=2020",
            "liquidgeneration.com/content/showmedacontent.aspx?cid=2222",
            "liquidgeneration.com/content/showmedacontent.aspx?cid=2268",
            "liquidgeneration.com/content/showmedacontent.aspx?cid=2307",
            "liquidgeneration.com/how-to-cook-the-perfect-hamburger",
            "liquidgeneration.com/media/animations/weird_random/sick_twisted/fire_safety_with_ready_fre",
            "liquidgeneration.com/media/pranks/fake_tests/all_fake_tests/are_you_going_to_heaven_or_hell",
            "liquidgeneration.com/media/pranks/fake_tests/all_fake_tests/online_fitness_check",
            "liquidgeneration.com/media/pranks/holiday/all_holiday/the_illusion_of_bloody_mary",
            "liquidgeneration.com/media/pranks/weird_random/all_weird_random/satanic_messages_in_music",
            "liquidgeneration.com/media/sabotage/divine_visions_of_mary__jesus",
            "liquidgeneration.com/media/sabotage/halloween_safety_tips_with_jack_o_lantern",
            "liquidgeneration.com/media/videos/lg_originals/other_lg_originals/watch_out_for_strangers",
            "liquidgeneration.com/media/videos/viral_videos/bizarre/optical_illusion_ames_window",
            "liquidgeneration.com/trick-or-treat",
            "martectx.de/whatswrong.swf",
            "meatspin.com",
            "meatspin.fr",
            "media.putfile.com/bnfjg",
            "media.putfile.com/britney-spears-hidden-message",
            "media.putfile.com/ghost-footage",
            "media.putfile.com/sexy-ice-cream-message",
            "media.putfile.com/tour-of-the-universe",
            "media.tumblr.com/tumblr_lft3yaxwva1qddxbt.gif",
            "members.home.nl/saen/special/zoeken.swf",
            "members.lycos.co.uk/martyncruise/scare.html",
            "members.multimania.co.uk/martyncruise/scream.html",
            "minecraft.swf",
            "monkeydoo.com/cool8.php?i=11131",
            "monkeydoo.com/onlineflash_remotescan.php",
            "monkeydoo.com/view/pranks/3/expert:_mouse_racing.html",
            "netbroadcaster.com/new/shorts/flash/viewswf.cgi",
            "newgrounds.com/portal/view/234890",
            "newgrounds.com/portal/view/279778",
            "newgrounds.com/portal/view/294974",
            "newgrounds.com/portal/view/301773",
            "newgrounds.com/portal/view/311234",
            "newgrounds.com/portal/view/43663",
            "newgrounds.com/portal/view/464999",
            "newgrounds.com/portal/view/475574",
            "newgrounds.com/portal/view/47612",
            "nobodyhere.com/justme/present.here",
            "ogrish.com",
            "ogrish.tv/play.php?vid=148",
            "online.sector.sk/hra.aspx?game=1368",
            "optillusions.com/dp/1-51.htm",
            "playerreview.net",
            "podrido.com/melodias",
            "pumba.swf",
            "putfile.com/2-ringed-ufo",
            "pyzam.com/tictactoe",
            "rabailkal.com/hypnose.htm",
            "rightxd.org",
            "rotten.com",
            "scaryforkids.com/pics/yahoo-search.htm",
            "shafou.com",
            "shinysearch.com/prank/fakegoogle.php?mode=demo",
            "shockchan.com/1-man-1-screwdriver",
            "sinthaistudio.com/alrena",
            "smartmindmedia.com/flash/play.php?id=camera&width=400&height=350",
            "spankwire.com",
            "specialfriedrice.net",
            "sscary.ru",
            "starterupsteve.com/swf/steadyhand.html",
            "strawpoii",
            "strawpoii.me",
            "subliminalmessages.com/p7b.htm",
            "subliminalmessages.com/p999.htm",
            "subliminalmessages.com/vip%20subliminal%2061a.htm",
            "sugarqube.com/ecards/cardview.cfm?cardid=1120&l1=1&l2=66&l3=0&page=",
            "sugarqube.com/ecards/cardview.cfm?cardid=1228",
            "sugarqube.com/ecards/cardview.cfm?cardid=1371&l1=186&l2=253&l3=0&page=",
            "superlaugh.com/1/waldo.htm",
            "testyoursenses.com",
            "thatguywiththeglasses.com/videolinks/thatguywiththeglasses/ask-thatguy/505-ask-thatguy-episode-5",
            "tubgirl.ca",
            "video.google.ca/videoplay?docid=-1552180646875208863&ei=30kgsuxre6bmqql7jbwxbw&hl=en",
            "video.google.com/videoplay?docid=-6344215419730491458&q=lost&pl=true",
            "video.google.com/videoplay?docid=-781295686117548807&hl=en",
            "video.google.com/videoplay?docid=5400390924456577745&hl=en",
            "vision.badgerville.org",
            "watch?v=-zh6e1fwq7o&feature=related",
            "watch?v=0ys2zguu5gg",
            "watch?v=1sexyy9pocs",
            "watch?v=1t9bgxqgths",
            "watch?v=39d3lebowbs",
            "watch?v=4eqz2rdahfg&feature=channel",
            "watch?v=4xjhorxrqiw",
            "watch?v=5hwqnssvaoa",
            "watch?v=5ir8pwydzo4",
            "watch?v=5wrsqt9f738",
            "watch?v=6-xtf3w1opk",
            "watch?v=6cp1h0fuig4",
            "watch?v=6o5j0pcrvje",
            "watch?v=6tbzyqn-62k",
            "watch?v=6zu9svx2l7a&feature=related",
            "watch?v=7cjrmuljakc",
            "watch?v=8d2pxc1tsvq",
            "watch?v=8w2pbnk3tka",
            "watch?v=8xo2x_62fqq",
            "watch?v=aasawjdrjfq",
            "watch?v=adlny0ciw4a",
            "watch?v=afk9x2iuuyc",
            "watch?v=auq3hmqwfrc",
            "watch?v=buxonoenm8a",
            "watch?v=c-de18t8efo",
            "watch?v=chqjrupkv9u",
            "watch?v=drep8080mz8",
            "watch?v=dsuz3og9kl0&feature=related",
            "watch?v=dtg1qy4q7mw",
            "watch?v=dtvodaquj3m",
            "watch?v=ec89gxfltt8",
            "watch?v=ehtujuxj9ai&feature=channel",
            "watch?v=ei0fn6ijd0o",
            "watch?v=epnwv3giwlg&feature=related",
            "watch?v=fp2u9nowxoy",
            "watch?v=hmu2ydip0bo",
            "watch?v=hwbjyihpuvi",
            "watch?v=iigda5q9egq",
            "watch?v=j1q-czzakq0",
            "watch?v=j3wk9ihetya&feature=related",
            "watch?v=jgxsdkakkke",
            "watch?v=jnn_uolut_i",
            "watch?v=k86685loths",
            "watch?v=kb1mjgy8xic",
            "watch?v=kpade6txi_q",
            "watch?v=kq3ixm3tg7q",
            "watch?v=kybc1rzjyye",
            "watch?v=l2c_movv1v8",
            "watch?v=ll03dliyv9c",
            "watch?v=lpccgflnw24",
            "watch?v=lund56xag4g",
            "watch?v=nbf4vv-clfq&feature=relmfu",
            "watch?v=nqoecxkxhcs",
            "watch?v=nt1tuuy_qq4",
            "watch?v=nv86johtzc4",
            "watch?v=nvldwxi3wds",
            "watch?v=nx0ugvkabsq",
            "watch?v=oiiaa3ul9pu",
            "watch?v=oqfcxths8re",
            "watch?v=pi3g_8_3_kk",
            "watch?v=pl_eblg45ew",
            "watch?v=pmqnqcmktss",
            "watch?v=pwkwzqdog0i",
            "watch?v=q5mriedpcz0",
            "watch?v=qco6noighgi",
            "watch?v=qiihriphk4y",
            "watch?v=qmpypcpiswc",
            "watch?v=qv6wluc9duc&feature=channel",
            "watch?v=rdrcxbl37pq",
            "watch?v=roprqyrbxkq",
            "watch?v=ruipj0kpgzi&feature=related",
            "watch?v=se8sgjla9ha",
            "watch?v=t49v2r5pg-0",
            "watch?v=vdk_puyvt4c",
            "watch?v=vfk74svzrzk",
            "watch?v=vpfygvordhi",
            "watch?v=vzikgcqc0us",
            "watch?v=wa4x_cvb-la&feature=related",
            "watch?v=wijf3xgq4ng",
            "watch?v=wy0c6vpr8_g&feature=related",
            "watch?v=wy88nnkid18",
            "watch?v=wz0o0lukhig",
            "watch?v=x0p32-y-q9g",
            "watch?v=yfyiheu-tvg",
            "watch?v=yo-viwpdgtq",
            "watch?v=yqzidpx0p-c",
            "watch?v=yts5zz-ooum",
            "watch?v=yzccz0sosz4",
            "watch?v=z21f6dfamji",
            "watch?v=zyc3c1kb0tg",
            "watch?v=zzkcrafz6gq",
            "web.archive.org/web/20081011044436/http://img165.imageshack.us/my.php?image=robluccithegame3gi.swf",
            "weebls-stuff.com/toons/taken",
            "weticecream.com",
            "whoomp.org",
            "winterrowd.com/bubblewrap",
            "winterrowd.com/exorcist",
            "winterrowd.com/hindu_life_tips",
            "winterrowd.com/hitthedot",
            "winterrowd.com/illusions.htm",
            "winterrowd.com/jeremy",
            "winterrowd.com/lostdog",
            "winterrowd.com/maze",
            "winterrowd.com/peeping-tom",
            "winterrowd.com/simon",
            "winterrowd.com/supermariobros",
            "winterrowd.com/swearing-baby",
            "winterrowd.com/ultimatemaze",
            "www.cadred.org/media/images/image/36016",
            "www.newgrounds.com/portal/view/452252",
            "x-rider.com",
            "yenimports.co.uk",
            "zerotec.comxa.com",
            "zerotec.net16.net"
        #endregion
        );
    }

    public static class UrlShortenerConstants
    {
        public static readonly ImmutableDictionary<string, string> UrlShorteners = new Dictionary<string, string> {
            #region URL_SHORTENERS
            ["06.hk"] = "http://urlshortener.org",
            ["0rz.tw"] = "http://0rz.tw",
            ["10.rs"] = "http://urlshortener.org",
            ["1iny.com"] = "http://urlshortener.org",
            ["1kh.de"] = "http://urlshortener.org",
            ["1link.in"] = "http://longurl.org/services",
            ["1tja.com"] = "N/A",
            ["1url.com"] = "http://www.mrbup.com",
            ["2.gp"] = "http://longurl.org/services",
            ["2big.at"] = "http://urlshortener.org",
            ["2tr.net"] = "http://urlshortener.org",
            ["2tu.us"] = "http://urlshortener.org",
            ["3.ly"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["307.to"] = "http://longurl.org/services",
            ["4ms.me"] = "http://longurl.org/services",
            ["4nu.net"] = "N/A",
            ["4sq.com"] = "http://longurl.org/services",
            ["4url.cc"] = "http://longurl.org/services",
            ["55c.cc"] = "http://urlshortener.org",
            ["6t4.us"] = "http://urlshortener.org",
            ["6url.com"] = "http://longurl.org/services",
            ["7.ly"] = "http://longurl.org/services",
            ["7les.com"] = "http://urlshortener.org",
            ["98.to"] = "http://98.to/tc/home.asp",
            ["a.gg"] = "http://longurl.org/services",
            ["a.nf"] = "http://longurl.org/services",
            ["a.nf"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["aa.cx"] = "http://longurl.org/services",
            ["abcurl.net"] = "http://longurl.org/services",
            ["abe5.com"] = "http://urlshortener.org",
            ["ad.vu"] = "http://longurl.org/services",
            ["adf.ly"] = "http://longurl.org/services",
            ["adjix.com"] = "http://longurl.org/services",
            ["aelita.fr"] = "http://www.jelev.eu/accueil.php",
            ["afx.cc"] = "http://longurl.org/services",
            ["all.fuseurl.com"] = "http://longurl.org/services",
            ["alturl.com"] = "http://longurl.org/services",
            ["amzn.to"] = "http://longurl.org/services",
            ["ao.co.za"] = "http://urlshortener.org",
            ["apu.sh"] = "http://urlshortener.org",
            ["ar.gy"] = "http://longurl.org/services",
            ["arm.in"] = "http://urlshortener.org",
            ["arst.ch"] = "http://longurl.org/services",
            ["atu.ca"] = "http://longurl.org/services",
            ["ax.ag"] = "http://urlshortener.org",
            ["azc.cc"] = "http://longurl.org/services",
            ["b00b.tk"] = "http://urlshortener.org",
            ["b23.ru"] = "http://longurl.org/services",
            ["b2l.me"] = "http://urlshortener.org",
            ["bacn.me"] = "http://longurl.org/services",
            ["bcool.bz"] = "http://longurl.org/services",
            ["biglnk.com"] = "http://urlshortener.org",
            ["binged.it"] = "http://longurl.org/services",
            ["bit.ly"] = "http://longurl.org/services",
            ["bizj.us"] = "http://longurl.org/services",
            ["bizy.be"] = "http://urlshortener.org",
            ["bizz.cc"] = "http://urlshortener.org",
            ["bloat.me"] = "http://longurl.org/services",
            ["bpt.st"] = "http://urlshortener.org",
            ["br.st"] = "http://urlshortener.org",
            ["bravo.ly"] = "http://longurl.org/services",
            ["bsa.ly"] = "http://longurl.org/services",
            ["budurl.com"] = "http://longurl.org/services",
            ["canurl.com"] = "http://urlshortener.org",
            ["cd4.me"] = "http://urlshortener.org",
            ["checkthislink.com"] = "http://urlshortener.org",
            ["chilp.it"] = "http://longurl.org/services",
            ["chrst.ph"] = "http://urlshortener.org",
            ["chs.mx"] = "http://urlshortener.org",
            ["chzb.gr"] = "http://longurl.org/services",
            ["cl.lk"] = "http://longurl.org/services",
            ["clck.ru"] = "http://urlshortener.org",
            ["cli.gs"] = "http://urlshortener.org",
            ["cliccami.info"] = "http://longurl.org/services",
            ["clickthru.ca"] = "http://longurl.org/services",
            ["clockurl.com"] = "http://urlshortener.org",
            ["clop.in"] = "http://urlshortener.org",
            ["co.nr"] = "http://www.freedomain.co.nr/",
            ["coge.la"] = "N/A",
            ["conta.cc"] = "http://longurl.org/services",
            ["cort.as"] = "http://urlshortener.org",
            ["cot.ag"] = "http://longurl.org/services",
            ["cr.am"] = "http://urlshortener.org",
            ["crks.me"] = "http://longurl.org/services",
            ["cru.ms"] = "http://urlshortener.org",
            ["ctvr.us"] = "http://longurl.org/services",
            ["cut.by"] = "http://urlshortener.org",
            ["cutt.us"] = "http://longurl.org/services",
            ["d3c.co"] = "N/A",
            ["dai.ly"] = "http://longurl.org/services",
            ["decenturl.com"] = "http://longurl.org/services",
            ["delivr.com"] = "http://urlshortener.org",
            ["devnull.at"] = "http://urlshortener.org",
            ["df9.net"] = "http://urlshortener.org",
            ["dfl8.me"] = "http://urlshortener.org",
            ["dickensurl.com"] = "http://urlshortener.org",
            ["digbig.com"] = "http://longurl.org/services",
            ["digg.com"] = "http://longurl.org/services",
            ["disq.us"] = "http://longurl.org/services",
            ["dld.bz"] = "http://longurl.org/services",
            ["dlvr.it"] = "http://longurl.org/services",
            ["do.my"] = "http://longurl.org/services",
            ["doiop.com"] = "http://urlshortener.org",
            ["dopen.us"] = "http://longurl.org/services",
            ["drv2.com"] = "http://urlshortener.org",
            ["dwarfurl.com"] = "http://urlshortener.org",
            ["dz.ly"] = "http://urlshortener.org",
            ["earlme.com"] = "http://urlshortener.org",
            ["easyurl.net"] = "http://longurl.org/services",
            ["eepurl.com"] = "http://longurl.org/services",
            ["eg3.net"] = "http://urlshortener.org",
            ["ekey.us"] = "http://urlshortener.org",
            ["elurl.com"] = "http://urlshortener.org",
            ["eweri.com"] = "http://longurl.org/services",
            ["fa.by"] = "http://longurl.org/services",
            ["fat.ly"] = "http://urlshortener.org",
            ["fav.me"] = "http://longurl.org/services",
            ["fb.me"] = "http://longurl.org/services",
            ["fbshare.me"] = "http://longurl.org/services",
            ["ff.im"] = "http://longurl.org/services",
            ["fff.to"] = "http://fff.to/",
            ["fhurl.com"] = "http://urlshortener.org",
            ["fire.to"] = "http://longurl.org/services",
            ["firsturl.de"] = "http://longurl.org/services",
            ["firsturl.net"] = "http://longurl.org/services",
            ["flib.in"] = "http://urlshortener.org",
            ["flic.kr"] = "http://longurl.org/services",
            ["flq.us"] = "http://urlshortener.org",
            ["fly2.ws"] = "http://longurl.org/services",
            ["flyfrm.com"] = "N/A",
            ["fon.gs"] = "http://longurl.org/services",
            ["forit.org"] = "http://urlshortener.org",
            ["forwarding.clockwatchers.com"] = "http://forwarding.clockwatchers.com",
            ["freak.to"] = "http://longurl.org/services",
            ["fuseurl.com"] = "http://longurl.org/services",
            ["fuzzy.to"] = "http://longurl.org/services",
            ["fwd4.me"] = "http://urlshortener.org",
            ["fwib.net"] = "http://longurl.org/services",
            ["g.ro.lt"] = "http://urlshortener.org",
            ["gentleurl.net"] = "http://urlshortener.org",
            ["gizmo.do"] = "http://longurl.org/services",
            ["gl.am"] = "http://urlshortener.org",
            ["gli.im"] = "N/A",
            ["go.9nl.com"] = "http://longurl.org/services",
            ["go.ign.com"] = "http://longurl.org/services",
            ["go.usa.gov"] = "http://longurl.org/services",
            ["go2.st"] = "http://urlshortener.org",
            ["goo.gl"] = "http://longurl.org/services",
            ["good.ly"] = "http://urlshortener.org",
            ["gop.am"] = "http://urlshortener.org",
            ["goshrink.com"] = "http://longurl.org/services",
            ["gsfn.info"] = "N/A",
            ["gu.ma"] = "http://urlshortener.org",
            ["gurl.es"] = "http://urlshortener.org",
            ["hex.io"] = "http://longurl.org/services",
            ["hi2.com"] = "N/A",
            ["hiderefer.com"] = "http://longurl.org/services",
            ["hmm.ph"] = "http://longurl.org/services",
            ["hop.im"] = "http://urlshortener.org",
            ["hostviet.biz"] = "http://urlshortener.org",
            ["hotshorturl.com"] = "http://urlshortener.org",
            ["hotshr.com"] = "http://urlshortener.org",
            ["href.in"] = "http://longurl.org/services",
            ["href.to"] = "http://urlshortener.org",
            ["hsblinks.com"] = "http://longurl.org/services",
            ["htxt.it"] = "http://longurl.org/services",
            ["hub.tm"] = "http://urlshortener.org",
            ["huff.to"] = "http://longurl.org/services",
            ["hulu.com"] = "http://longurl.org/services",
            ["hurl.me"] = "http://urlshortener.org",
            ["hurl.ws"] = "http://urlshortener.org",
            ["icanhaz.com"] = "http://urlshortener.org",
            ["idek.net"] = "http://urlshortener.org",
            ["ikr.me"] = "http://urlshortener.org",
            ["ilix.in"] = "http://longurl.org/services",
            ["imfy.us"] = "http://urlshortener.org",
            ["in2s.us"] = "http://urlshortener.org",
            ["inturl.com"] = "http://urlshortener.org",
            ["ion.so"] = "N/A",
            ["is.gd"] = "http://urlshortener.org",
            ["it1.nl"] = "http://urlshortener.org",
            ["ito.mx"] = "http://urlshortener.org",
            ["its.my"] = "http://longurl.org/services",
            ["ix.lt"] = "http://longurl.org/services",
            ["j.mp"] = "http://longurl.org/services",
            ["jelev.eu"] = "http://www.jelev.eu/accueil.php",
            ["jesais.fr"] = "http://www.jelev.eu/accueil.php",
            ["jesais.fr"] = "http://www.jelev.eu/accueil.php",
            ["jijr.com"] = "http://longurl.org/services",
            ["joturl.com"] = "http://www.joturl.comS",
            ["jtefaisla.biz"] = "http://www.jelev.eu/accueil.php",
            ["ju.nu"] = "http://urlshortener.org",
            ["kaano.info"] = "http://urlshortener.org",
            ["ki.tl"] = "http://urlshortener.org",
            ["kissa.be"] = "http://urlshortener.org",
            ["kiwiurl.com"] = "http://urlshortener.org",
            ["kl.am"] = "http://urlshortener.org",
            ["klck.me"] = "http://longurl.org/services",
            ["korta.nu"] = "http://urlshortener.org",
            ["krunchd.com"] = "http://urlshortener.org",
            ["krz.ch"] = "http://urlshortener.org",
            ["ks.gs"] = "N/A",
            ["kuerzer.de"] = "http://urlshortener.org",
            ["kwik.to"] = "http://sitelutions.com",
            ["kxk.me"] = "http://urlshortener.org",
            ["l.pr"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["l9k.net"] = "http://longurl.org/services",
            ["lacheun.com"] = "http://www.jelev.eu/accueil.php",
            ["lamped.co.uk"] = "http://urlshortener.org",
            ["lat.ms"] = "http://longurl.org/services",
            ["lawurl.com"] = "N/A",
            ["lb.vg"] = "http://urlshortener.org",
            ["liip.to"] = "http://longurl.org/services",
            ["liltext.com"] = "http://longurl.org/services",
            ["linkasa.com"] = "http://urlshortener.org",
            ["linkbee.com"] = "http://urlshortener.org",
            ["linkbun.ch"] = "http://longurl.org/services",
            ["linkfrog.net"] = "http://urlshortener.org",
            ["linkpeak.com"] = "http://urlshortener.org",
            ["liteurl.com"] = "http://urlshortener.org",
            ["liurl.cn"] = "http://urlshortener.org",
            ["lllll.im"] = "N/A",
            ["ln-s.net"] = "http://longurl.org/services",
            ["ln-s.ru"] = "http://longurl.org/services",
            ["lnk.by"] = "http://urlshortener.org",
            ["lnk.gd"] = "http://longurl.org/services",
            ["lnk.ms"] = "http://longurl.org/services",
            ["lnkd.in"] = "http://longurl.org/services",
            ["lnkurl.com"] = "http://longurl.org/services",
            ["lru.jp"] = "http://longurl.org/services",
            ["lt.tl"] = "http://longurl.org/services",
            ["lurl.no"] = "http://longurl.org/services",
            ["lymme.com"] = "http://urlshortener.org",
            ["lyoko.eu"] = "http://www.jelev.eu/accueil.php",
            ["macte.ch"] = "http://longurl.org/services",
            ["mash.to"] = "http://longurl.org/services",
            ["mattemon.info"] = "http://www.jelev.eu/accueil.php",
            ["memurl.com"] = "http://urlshortener.org",
            ["merky.de"] = "http://longurl.org/services",
            ["metamark.net"] = "http://urlshortener.org",
            ["migre.me"] = "http://longurl.org/services",
            ["minify.me"] = "http://urlshortener.org",
            ["minilien.com"] = "http://urlshortener.org",
            ["minilink.org"] = "http://urlshortener.org",
            ["miniurl.com"] = "http://longurl.org/services",
            ["minu.me"] = "http://urlshortener.org",
            ["minurl.fr"] = "http://longurl.org/services",
            ["minyurl.net"] = "http://urlshortener.org",
            ["mke.me"] = "http://longurl.org/services",
            ["moby.to"] = "http://longurl.org/services",
            ["monbe.be"] = "http://www.jelev.eu/accueil.php",
            ["monbe.be"] = "N/A",
            ["moourl.com"] = "http://urlshortener.org",
            ["mrte.ch"] = "http://longurl.org/services",
            ["multiurl.com"] = "http://urlshortener.org",
            ["mylnk.us"] = "http://urlshortener.org",
            ["myloc.me"] = "http://longurl.org/services",
            ["myurl.in"] = "http://urlshortener.org",
            ["myurlz.com"] = "http://urlshortener.org",
            ["n.pr"] = "http://longurl.org/services",
            ["nbc.co"] = "http://longurl.org/services",
            ["nblo.gs"] = "http://longurl.org/services",
            ["ncane.com"] = "http://urlshortener.org",
            ["ne8.org"] = "http://urlshortener.org",
            ["netnet.me"] = "http://urlshortener.org",
            ["ni2.in"] = "http://urlshortener.org",
            ["ninjalink.com"] = "http://urlshortener.org",
            ["niy.me"] = "N/A",
            ["nn.nf"] = "http://longurl.org/services",
            ["no1.in"] = "http://urlshortener.org",
            ["normalurl.com"] = "http://urlshortener.org",
            ["not.my"] = "http://longurl.org/services",
            ["notlong.com"] = "http://urlshortener.org",
            ["nsfw.in"] = "http://longurl.org/services",
            ["nutshellurl.com"] = "http://longurl.org/services",
            ["nuurl.us"] = "http://urlshortener.org",
            ["nxy.in"] = "http://longurl.org/services",
            ["nyti.ms"] = "http://longurl.org/services",
            ["nznet.info"] = "N/A",
            ["o-x.fr"] = "http://urlshortener.org",
            ["oc1.us"] = "http://longurl.org/services",
            ["ohurl.com"] = "http://urlshortener.org",
            ["om.ly"] = "http://longurl.org/services",
            ["omf.gd"] = "http://longurl.org/services",
            ["omoikane.net"] = "http://longurl.org/services",
            ["on.cnn.com"] = "http://longurl.org/services",
            ["on.mktw.net"] = "http://longurl.org/services",
            ["onforb.es"] = "http://longurl.org/services",
            ["orkurl.com"] = "http://urlshortener.org",
            ["orz.se"] = "http://longurl.org/services",
            ["oueb.eu"] = "http://www.jelev.eu/accueil.php",
            ["ow.ly"] = "http://urlshortener.org",
            ["p.gs"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["p.ly"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["parv.us"] = "http://urlshortener.org",
            ["pic.gd"] = "http://urlshortener.org",
            ["picsorlinks.com"] = "http://urlshortener.org",
            ["ping.fm"] = "http://longurl.org/services",
            ["piurl.com"] = "http://urlshortener.org",
            ["pli.gs"] = "http://longurl.org/services",
            ["pnt.me"] = "http://urlshortener.org",
            ["politi.co"] = "http://longurl.org/services",
            ["ponyurl.com"] = "http://urlshortener.org",
            ["post.ly"] = "http://longurl.org/services",
            ["pourle.net"] = "http://www.jelev.eu/accueil.php",
            ["pp.gg"] = "http://longurl.org/services",
            ["pr0n.net"] = "http://urlshortener.org",
            ["profile.to"] = "http://longurl.org/services",
            ["ptiturl.com"] = "http://urlshortener.org",
            ["pub.vitrue.com"] = "http://longurl.org/services",
            ["pwr.com"] = "http://urlshortener.org",
            ["qlnk.net"] = "http://urlshortener.org",
            ["qte.me"] = "http://longurl.org/services",
            ["qu.tc"] = "http://longurl.org/services",
            ["qurlyq.com"] = "http://urlshortener.org",
            ["quu.nu"] = "http://urlshortener.org",
            ["qwer.org"] = "http://urlshortener.org",
            ["qwx.si"] = "http://urlshortener.org",
            ["qy.fi"] = "http://longurl.org/services",
            ["r.im"] = "http://longurl.org/services",
            ["rb6.me"] = "http://urlshortener.org",
            ["rcez.info"] = "http://urlshortener.org",
            ["rde.me"] = "http://urlshortener.org",
            ["read.bi"] = "http://longurl.org/services",
            ["readthis.ca"] = "http://longurl.org/services",
            ["reallytinyurl.com"] = "http://longurl.org/services",
            ["redir.ec"] = "http://longurl.org/services",
            ["redir.ec"] = "http://urlshortener.org",
            ["redirects.ca"] = "http://longurl.org/services",
            ["redirx.com"] = "http://urlshortener.org",
            ["relurl.com"] = "http://urlshortener.org",
            ["retwt.me"] = "http://urlshortener.org",
            ["ri.ms"] = "http://longurl.org/services",
            ["rickroll.it"] = "http://longurl.org/services",
            ["riz.gd"] = "http://longurl.org/services",
            ["rt.nu"] = "http://longurl.org/services",
            ["ru.ly"] = "http://longurl.org/services",
            ["rubyurl.com"] = "http://longurl.org/services",
            ["rurl.org"] = "http://longurl.org/services",
            ["rww.tw"] = "http://longurl.org/services",
            ["s4c.in"] = "http://longurl.org/services",
            ["s7y.us"] = "http://urlshortener.org",
            ["safe.mn"] = "http://longurl.org/services",
            ["sameurl.com"] = "http://longurl.org/services",
            ["scrnch.me"] = "http://urlshortener.org",
            ["sdut.us"] = "http://longurl.org/services",
            ["sendtourl.com"] = "N/A",
            ["shar.es"] = "http://longurl.org/services",
            ["shink.de"] = "http://longurl.org/services",
            ["sho.li"] = "http://urlshortener.org",
            ["shoor.tk"] = "N/A",
            ["shorl.com"] = "http://urlshortener.org",
            ["short.ie"] = "http://longurl.org/services",
            ["short.to"] = "http://urlshortener.org",
            ["shorten.ws"] = "http://urlshortener.org",
            ["shortlinks.co.uk"] = "http://longurl.org/services",
            ["shortna.me"] = "http://urlshortener.org",
            ["shortner.com"] = "http://urlshortener.org",
            ["shorturl.com"] = "http://longurl.org/services",
            ["shout.to"] = "http://longurl.org/services",
            ["show.my"] = "http://longurl.org/services",
            ["shrinkify.com"] = "http://longurl.org/services",
            ["shrinkr.com"] = "http://longurl.org/services",
            ["shrt.fr"] = "http://longurl.org/services",
            ["shrt.st"] = "http://longurl.org/services",
            ["shrten.com"] = "http://longurl.org/services",
            ["shrunkin.com"] = "http://longurl.org/services",
            ["shrvl.com"] = "http://urlshortener.org",
            ["shw.me"] = "http://urlshortener.org",
            ["simurl.com"] = "http://longurl.org/services",
            ["simurl.com"] = "http://urlshortener.org",
            ["sl.ly"] = "http://urlshortener.org",
            ["slate.me"] = "http://longurl.org/services",
            ["slnk.me"] = "http://urlshortener.org",
            ["smal.ly"] = "http://urlshortener.org",
            ["smallr.com"] = "http://urlshortener.org",
            ["smll.me"] = "http://smll.me",
            ["smlurl.info"] = "N/A",
            ["smrls.tk"] = "http://urlshortener.org",
            ["smsh.me"] = "http://longurl.org/services",
            ["smurl.lv"] = "http://urlshortener.org",
            ["smurl.name"] = "http://longurl.org/services",
            ["sn.im"] = "http://longurl.org/services",
            ["snipr.com"] = "http://longurl.org/services",
            ["snipurl.com"] = "http://urlshortener.org",
            ["snurl.com"] = "http://longurl.org/services",
            ["sp2.ro"] = "http://urlshortener.org",
            ["spedr.com"] = "http://longurl.org/services",
            ["sqze.it"] = "http://long-shore.com/expand",
            ["sra.li"] = "N/A",
            ["srnk.it"] = "http://urlshortener.org",
            ["srnk.net"] = "http://longurl.org/services",
            ["srs.li"] = "http://longurl.org/services",
            ["starturl.com"] = "http://urlshortener.org",
            ["sturly.com"] = "http://urlshortener.org",
            ["su.pr"] = "http://urlshortener.org",
            ["surl.co.uk"] = "http://longurl.org/services",
            ["surl.co.uk"] = "http://urlshortener.org",
            ["surl.hu"] = "http://longurl.org/services",
            ["t.co"] = "http://longurl.org/services",
            ["t.lh.com"] = "http://longurl.org/services",
            ["ta.gd"] = "http://urlshortener.org",
            ["tak.bz"] = "http://urlshortener.org",
            ["takeme.to"] = "http://urlshortener.org",
            ["tbd.ly"] = "http://longurl.org/services",
            ["tcrn.ch"] = "http://longurl.org/services",
            ["te.tl"] = "http://urlshortener.org",
            ["tgr.me"] = "http://longurl.org/services",
            ["tgr.ph"] = "http://longurl.org/services",
            ["thecow.me"] = "http://urlshortener.org",
            ["tighturl.com"] = "http://urlshortener.org",
            ["tiniuri.com"] = "http://longurl.org/services",
            ["tiny.cc"] = "http://urlshortener.org",
            ["tiny.ly"] = "http://longurl.org/services",
            ["tiny.pl"] = "http://urlshortener.org",
            ["tiny.tw"] = "N/A",
            ["tiny2go.com"] = "http://urlshortener.org",
            ["tinyftw.com"] = "http://urlshortener.org",
            ["tinylink.in"] = "http://longurl.org/services",
            ["tinyuri.ca"] = "http://longurl.org/services",
            ["tinyurl.com"] = "http://urlshortener.org",
            ["tl.gd"] = "http://longurl.org/services",
            ["tmi.me"] = "http://longurl.org/services",
            ["tnij.org"] = "http://longurl.org/services",
            ["tnw.to"] = "http://longurl.org/services",
            ["tny.com"] = "http://longurl.org/services",
            ["to.ly"] = "http://longurl.org/services",
            ["togoto.us"] = "http://longurl.org/services",
            ["totc.us"] = "http://longurl.org/services",
            ["toysr.us"] = "http://longurl.org/services",
            ["tpm.ly"] = "http://longurl.org/services",
            ["tr.im"] = "http://longurl.org/services",
            ["tra.kz"] = "http://urlshortener.org",
            ["trunc.it"] = "http://urlshortener.org",
            ["tuaurl.com"] = "http://urlshortener.org",
            ["turls.me"] = "http://urlshortener.org",
            ["tutz.me"] = "http://urlshortener.org",
            ["tw3.it"] = "http://urlshortener.org",
            ["tweak.tk"] = "http://urlshortener.org",
            ["tweez.me"] = "http://urlshortener.org",
            ["twhub.com"] = "http://longurl.org/services",
            ["twi.tl"] = "http://urlshortener.org",
            ["twirl.at"] = "http://longurl.org/services",
            ["twitclicks.com"] = "http://longurl.org/services",
            ["twitterto.com"] = "http://urlshortener.org",
            ["twitterurl.net"] = "http://urlshortener.org",
            ["twitterurl.org"] = "http://longurl.org/services",
            ["twiturl.de"] = "http://urlshortener.org",
            ["twurl.cc"] = "http://longurl.org/services",
            ["twurl.nl"] = "http://urlshortener.org",
            ["u.go2.me"] = "http://urlshortener.org",
            ["u.mavrev.com"] = "http://longurl.org/services",
            ["u.nu"] = "http://longurl.org/services",
            ["u76.org"] = "http://longurl.org/services",
            ["ub0.cc"] = "http://longurl.org/services",
            ["ulu.lu"] = "http://longurl.org/services",
            ["updating.me"] = "http://longurl.org/services",
            ["ur1.ca"] = "http://longurl.org/services",
            ["url.az"] = "http://longurl.org/services",
            ["url.co.uk"] = "http://longurl.org/services",
            ["url.ie"] = "http://urlshortener.org",
            ["url.in.it"] = "N/A",
            ["url.to.it"] = "http://urlshortener.org",
            ["url360.me"] = "http://longurl.org/services",
            ["url4.eu"] = "http://longurl.org/services",
            ["urlbit.us"] = "http://urlshortener.org",
            ["urlborg.com"] = "http://longurl.org/services",
            ["urlbrief.com"] = "http://longurl.org/services",
            ["urlcover.com"] = "http://urlshortener.org",
            ["urlcut.com"] = "http://longurl.org/services",
            ["urlenco.de"] = "http://longurl.org/services",
            ["urli.nl"] = "http://longurl.org/services",
            ["urlit.net"] = "http://urlshortener.org",
            ["urlminifier.com"] = "http://urlshortener.org",
            ["urlmorph.com"] = "http://urlshortener.org",
            ["urlpire.com"] = "http://urlshortener.org",
            ["urls.im"] = "http://longurl.org/services",
            ["urlx.ie"] = "http://longurl.org/services",
            ["urlxp.com"] = "http://urlshortener.org",
            ["urlzen.com"] = "http://longurl.org/services",
            ["usat.ly"] = "http://longurl.org/services",
            ["use.my"] = "http://longurl.org/services",
            ["ushort.co.uk"] = "http://urlshortener.org",
            ["ux.lv"] = "http://urlshortener.org",
            ["vani.sh"] = "http://urlshortener.org",
            ["vb.ly"] = "http://longurl.org/services",
            ["vgn.am"] = "http://longurl.org/services",
            ["viewista.com"] = "http://urlshortener.org",
            ["virl.com"] = "http://urlshortener.org",
            ["vl.am"] = "http://longurl.org/services",
            ["vm.lc"] = "http://longurl.org/services",
            ["vs0.net"] = "N/A",
            ["w0p.de"] = "http://urlshortener.org",
            ["w55.de"] = "http://longurl.org/services",
            ["wapo.st"] = "http://longurl.org/services",
            ["wapurl.co.uk"] = "http://longurl.org/services",
            ["webalias.com"] = "http://urlshortener.org",
            ["weshort.in"] = "http://urlshortener.org",
            ["whit.me"] = "http://urlshortener.org",
            ["widg.me"] = "N/A",
            ["wipi.es"] = "http://longurl.org/services",
            ["wp.me"] = "http://longurl.org/services",
            ["wurl.ca"] = "http://urlshortener.org",
            ["wurl.ws"] = "http://urlshortener.org",
            ["wva.gd"] = "http://urlshortener.org",
            ["wwb.in"] = "http://urlshortener.org",
            ["x.co"] = "http://app.x.co/",
            ["x.se"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["x.vu"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["x2t.com"] = "http://urlshortener.org",
            ["xa.ly"] = "http://xa.ly/",
            ["xaddr.com"] = "http://urlshortener.org",
            ["xana.fr"] = "http://www.jelev.eu/accueil.php",
            ["xiy.net"] = "http://urlshortener.org",
            ["xpnd.it"] = "http://long-shore.com/expand",
            ["xr.com"] = "http://urlshortener.org",
            ["xrl.in"] = "http://longurl.org/services",
            ["xrl.us"] = "http://longurl.org/services",
            ["xurl.es"] = "http://longurl.org/services",
            ["xurl.jp"] = "http://urlshortener.org",
            ["y.ahoo.it"] = "http://longurl.org/services",
            ["yatuc.com"] = "http://longurl.org/services",
            ["ye.pe"] = "http://longurl.org/services",
            ["yep.it"] = "http://urlshortener.org",
            ["yfrog.com"] = "http://longurl.org/services",
            ["yhoo.it"] = "http://longurl.org/services",
            ["yi.pe"] = "N/A",
            ["yiyd.com"] = "http://longurl.org/services",
            ["yuarel.com"] = "http://longurl.org/services",
            ["yvy.me"] = "http://yvy.me/",
            ["z.pe"] = "http://urlshortener.org/one_character_url_shorteners/",
            ["z0p.de"] = "http://longurl.org/services",
            ["zapit.nu"] = "http://urlshortener.org",
            ["zeek.us"] = "http://urlshortener.org",
            ["zi.ma"] = "http://longurl.org/services",
            ["zi.mu"] = "http://longurl.org/services",
            ["zipmyurl.com"] = "http://longurl.org/services",
            ["ziprl.com"] = "http://urlshortener.org",
            ["zkracene.cz"] = "http://zkracene.cz/",
            ["zolp.net"] = "N/A",
            ["zud.me"] = "http://longurl.org/services",
            ["zurl.ws"] = "http://urlshortener.org",
            ["zwap.to"] = "http://urlshortener.org",
            ["zxc9.com"] = "http://urlshortener.org",
            ["zz.gd"] = "http://longurl.org/services",
            ["zzang.kr"] = "http://longurl.org/services",
            ["zzz.ee"] = "http://urlshortener.org",
            #endregion
        }.ToImmutableDictionary();

        public static readonly LinkfilterMatcher UrlShortenerRegex = new LinkfilterMatcher(UrlShorteners.Keys);
    }
}

